<?php

namespace SiteBDE\ShopBundle\Repository;

/**
 * ProductLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLangRepository extends \Doctrine\ORM\EntityRepository
{
}
