<?php

namespace SiteBDE\UserSystemBundle\Repository;

/**
 * AuthorisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
