<?php

namespace SiteBDE\UserSystemBundle\Repository;

/**
 * StatusLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusLangRepository extends \Doctrine\ORM\EntityRepository
{
}
