site_bde_user_system:
    resource: "@SiteBDEUserSystemBundle/Resources/config/routing.yml"
    prefix:   /User

site_bde_news:
    resource: "@SiteBDENewsBundle/Resources/config/routing.yml"
    prefix:   /News

site_bde_event:
    resource: "@SiteBDEEventBundle/Resources/config/routing.yml"
    prefix:   /Event

site_bde_shop:
    resource: "@SiteBDEShopBundle/Resources/config/routing.yml"
    prefix:   /Shop

site_bde_home_page:
    resource: "@SiteBDEHomePageBundle/Resources/config/routing.yml"
    prefix:   /

