<?php

namespace SiteBDE\NewsBundle\Repository;

/**
 * ArticleLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLangRepository extends \Doctrine\ORM\EntityRepository
{
}
