<?php

namespace SiteBDE\HomePageBundle\Repository;

/**
 * PageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
