<?php

namespace SiteBDE\EventBundle\Repository;

/**
 * EventLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLangRepository extends \Doctrine\ORM\EntityRepository
{
}
