site_bde_event_homepage:
    path:     /Event
    defaults: { _controller: SiteBDEEventBundle:Event:index }

    site_bde_event_homepage:
    path:     /FormulaireEvent
    defaults: { _controller: SiteBDEEventBundle:FormulaireEvent:index }

