site_bde_event_homepage:
    path:     /Event
    defaults: { _controller: SiteBDEEventBundle:Event:index }

site_bde_event_Form:
    path:     /FormEvent
    defaults: { _controller: SiteBDEEventBundle:FormEvent:index }

site_bde_event_Gallery:
    path:     /Gallery
    defaults: { _controller: SiteBDEEventBundle:Gallery:index }
<<<<<<< HEAD
    
 site_bde_event_List:
=======

site_bde_event_List:
>>>>>>> origin/master
    path:     /List
    defaults: { _controller: SiteBDEEventBundle:EventList:EventList }