site_bde_event_homepage:
    path:     /Event
    defaults: { _controller: SiteBDEEventBundle:Event:index }

site_bde_event_Form:
    path:     /FormEvent
    defaults: { _controller: SiteBDEEventBundle:FormEvent:index }


 