site_bde_event_homepage:
    path:     /Event
    defaults: { _controller: SiteBDEEventBundle:Event:index }

site_bde_event_Form:
    path:     /FormEvent
    defaults: { _controller: SiteBDEEventBundle:FormEvent:index }

site_bde_event_List:
    path:     /List
    defaults: { _controller: SiteBDEEventBundle:EventList:EventList }


site_bde_create_event_Form:
    path:     /CreateFormEvent
    defaults: { _controller: SiteBDEEventBundle:EventParticipation:addForm }